from tkinter import *


root = Tk()

Label_1 =Label(root ,text="TWBC",font=("Copperplate Gothic Bold" , 20))
Label_2 =Label(root ,text="NUT",font=("Copperplate Gothic Bold" , 20))
Label_3 =Label(root ,text="LYM",font=("Copperplate Gothic Bold" , 20))
Label_4 =Label(root ,text="EOS",font=("Copperplate Gothic Bold" , 20))
Label_5 =Label(root ,text="MON",font=("Copperplate Gothic Bold" , 20))
Label_6 =Label(root ,text="BAS",font=("Copperplate Gothic Bold" , 20))
Label_7 =Label(root ,text="PLT",font=("Copperplate Gothic Bold" , 20))
Label_8 =Label(root ,text=" HB",font=("Copperplate Gothic Bold" , 20))
Label_9 =Label(root ,text="PVC",font=("Copperplate Gothic Bold" , 20))
Label_10 =Label(root,text="RBC",font=("Copperplate Gothic Bold" , 20))
Label_11 =Label(root,text="MVC",font=("Copperplate Gothic Bold" , 20))
Label_12 =Label(root,text="MCH",font=("Copperplate Gothic Bold" , 20))
Label_13 =Label(root,text="MCHC",font=("Copperplate Gothic Bold" , 20))

Label_1.grid(row  = 1  , column = 0 )
Label_2.grid(row  = 2 , column =  0)
Label_3.grid(row  = 3 , column =  0)
Label_4.grid(row  = 4 , column =  0)
Label_5.grid(row  = 5 , column =  0)
Label_6.grid(row  = 6 , column =  0)
Label_7.grid(row  = 7 , column =  0)
Label_8.grid(row  = 8 , column =  0)
Label_9.grid(row  = 9 , column =  0)
Label_10.grid(row = 10, column =  0)
Label_11.grid(row = 11, column =  0)
Label_12.grid(row = 12, column =  0)
Label_13.grid(row = 13 , column = 0)

e1 = Entry(root)
e2 = Entry(root)
e3 = Entry(root)
e4 = Entry(root)
e5 = Entry(root)
e6 = Entry(root)
e7 = Entry(root)
e8 = Entry(root)
e9 = Entry(root)
e10 = Entry(root)
e11 = Entry(root)
e12 = Entry(root)
e13 = Entry(root)

e1.grid(row = 1 , column = 3 )
e2.grid(row = 2 , column = 3)
e3.grid(row = 3 , column = 3)
e4.grid(row = 4 , column = 3)
e5.grid(row = 5 , column = 3)
e6.grid(row = 6 , column = 3)
e7.grid(row = 7 , column = 3)
e8.grid(row = 8 , column = 3)
e9.grid(row = 9 , column = 3)
e10.grid(row =10 , column = 3)
e11.grid(row = 11, column = 3)
e12.grid(row =12 , column = 3)
e13.grid(row = 13, column = 3)

Label_10 = Label(root , text="/mm<sup>3</sup>",font=("Copperplate Gothic Bold" , 14))
Label_11 = Label(root , text="%", font=("Copperplate Gothic Bold" , 14))
Label_12 = Label(root , text="%", font=("Copperplate Gothic Bold" , 14))
Label_13 = Label(root , text="%", font=("Copperplate Gothic Bold" , 14))
Label_14 = Label(root , text="%", font=("Copperplate Gothic Bold" , 14))
Label_15 = Label(root , text="/mm<sup>3</sup>", font=("Copperplate Gothic Bold" , 14))
Label_16 = Label(root , text="g / dl", font=("Copperplate Gothic Bold" , 14))
Label_17 = Label(root , text="%", font=("Copperplate Gothic Bold" , 14))
Label_18 = Label(root , text="ul", font=("Copperplate Gothic Bold" , 14))
Label_19 = Label(root , text="fL", font=("Copperplate Gothic Bold" , 14))
Label_20 = Label(root , text="pg", font=("Copperplate Gothic Bold" , 14))
Label_21 = Label(root , text="g / dl", font=("Copperplate Gothic Bold" , 14))
Label_22 = Label(root , text="/mm<sup>3</sup>", font=("Copperplate Gothic Bold" , 14))

Label_10.grid(row = 1  , column = 6)
Label_11.grid(row = 2 , column = 6)
Label_12.grid(row = 3 , column = 6)
Label_13.grid(row =  4, column = 6)
Label_14.grid(row =  5, column = 6)
Label_15.grid(row =  6, column = 6)
Label_16.grid(row =  7, column = 6)
Label_17.grid(row =  8, column = 6)
Label_18.grid(row =  9, column = 6)
Label_19.grid(row =  10, column =6 )
Label_20.grid(row =  11, column =6 )
Label_21.grid(row =  12, column =6 )
Label_22.grid(row =  13, column =6 )



root.mainloop()